---
title: "numeric_eda"
output: html_document
date: "2022-10-06"
---
```{r}
library(tidyverse)
library(patchwork)
library(ggridges)
options(tibble.print_max = 6)
```

```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
```

## group by

```{r}
weather_df %>%
  group_by(name, month) %>% 
  summarize(n_obs = n())
```

```{r}
weather_df %>%
  count(month, name = "n_obs") 
```

don't use table
```{r}
weather_df %>%
  pull(month) %>% 
  table
```

```{r}
weather_df %>%
  group_by(month) %>%
  summarize(
    n_obs = n(),
    n_dist = n_distinct(date))
```

## 2*2 tables
```{r}
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ "THERE IS A PROBLEM"
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  group_by(name, cold) %>% 
  summarize(count = n()) %>% 
  pivot_wider(
    names_from = "cold",
    values_from = "count"
  )
```

```{r}
weather_df %>% 
  mutate(cold = case_when(
    tmax <  5 ~ "cold",
    tmax >= 5 ~ "not_cold",
    TRUE     ~ "THERE IS A PROBLEM"
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  janitor::tabyl(name, cold)
```

```{r}
weather_df %>%
  group_by(month) %>%
  summarize(
    mean_tmax = mean(tmax),
    mean_prec = mean(prcp, na.rm = TRUE),
    median_tmax = median(tmax),
    sd_tmax = sd(tmax)) %>% 
  view()
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(
    mean_tmax = mean(tmax),
    median_tmax = median(tmax))
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(across(tmin:prcp, mean))
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>%
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax) %>% 
  knitr::kable(digits = 1) %>% 
  view()
```



